### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Nickelony** [punker76/Avalonia.DragDrop#1]
I don't quite get how this code is even supposed to work. It feels like there's tons of crucial code missing.
Is that one class all there is in this library?

**Comment by punker76** [comment]
@Nickelony Yeah, sorry. I still working on it, so it's not ready yet. Thx

**Comment by McoreD** [comment]
Okay thanks for the update. I was thinking the same. I am trying to implement the feature to https://github.com/McoreD/UploaderX

**Comment by NeverMorewd** [comment]
May I ask if there are any plans for future updates to this repository? Thanks
